### ISSUE TITLE
simple live test does not work

### ISSUE THREAD

**Issue by limbo127** [LouisT/termbacktime#100]
**Describe the bug**
simple live test does not work ( from main git)
./termbacktime live  not work as expected 

Loaded config: /home/xxx/.termbacktime.json

A new version of termbacktime is available: v1.0.0-rc.8 (current 0.0.0)

Access granted: [turn:turn.termbackti.me:5349]
Username: 1644943633-2405a3b0-64ff-4cdf-8fdc-293b37089bc8
Password: Q3e4D225CwQ41NX5OTvlaqq4HaU=

Live playback: https://xterm.live/tbt:f728062c-68ff-490a-b3ef-a7b0dba8a5f5
Waiting for connection; timeout in 106 seconds... Connected.

**To Reproduce**
./termbacktime live  not work as expected 

Loaded config: /home/xxx/.termbacktime.json

A new version of termbacktime is available: v1.0.0-rc.8 (current 0.0.0)

Access granted: [turn:turn.termbackti.me:5349]
Username: 1644943633-2405a3b0-64ff-4cdf-8fdc-293b37089bc8
Password: Q3e4D225CwQ41NX5OTvlaqq4HaU=

Live playback: https://xterm.live/tbt:f728062c-68ff-490a-b3ef-a7b0dba8a5f5
Waiting for connection; timeout in 106 seconds... Connected.

then connect from firefox on https://xterm.live/tbt:f728062c-68ff-490a-b3ef-a7b0dba8a5f5

=> 
Error: unexpected EOF

panic: close of closed channel

goroutine 97 [running]:
louist.dev/termbacktime/cmd.glob..func4.7()
        /tmp/termbacktime/cmd/live.go:229 +0x6ce
created by louist.dev/termbacktime/cmd.glob..func4
        /tmp/termbacktime/cmd/live.go:223 +0x1fa5

***$ ./termbacktime -v
termbacktime - https://termbackti.me/ - version=0.0.0 revision=0000000 (go1.17)
 uname -a 
Linux localhost.localdomain 5.15.7-200.fc35.x86_64 #1 SMP Wed Dec 8 19:00:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by LouisT** [comment]
Alright, looking at your version string, it seems termbacktime CLI hasn't been installed properly. There are a few ways to do this using the [install bash script](https://raw.githubusercontent.com/termbacktime/termbacktime/master/install.sh), `go get` or from the git directory with Makefile.

Optionally if you wish to use [upx]( https://upx.github.io/) to further optimize the resulting binaries with **Method 2** or **Method 3** replace `make install` with `make install-upx`.  The `install.sh`  script will automatically attempt this at the end.

#### Method 1 (recommended):
This will also install the newest version of Go if it isn't detected.
```shell
curl -s -L https://termbackti.me/install.sh | bash
```
As well you can select which version of Go to install.
```shell
 wget https://termbackti.me/install.sh
 ./install.sh <version>
```

#### Method 2:
If go is already installed and your `$GOPATH` is set, you can `go get` a copy of termbacktime.
```shell
go get -u louist.dev/termbacktime
cd $GOPATH/src/louist.dev/termbacktime
make install
```
If you want to use upx here, you replace the `make install` with `make install-upx`.


#### Method 3:
You can pull a copy of termbacktime using git and compiling it with the Makefile.
```shell
git clone https://github.com/termbacktime/termbacktime.git
cd termbacktime 
make install
```

## Optional pre-compiled binaries:
There are some binaries available (that are currently outdated from master) that can also be used. The next release will be v1.0.0 which will be when these binaries are updated to match master. [v1.0.0-rc.7](https://github.com/termbacktime/termbacktime/releases/tag/v1.0.0-rc.7)

**Comment by limbo127** [comment]
I do not understand
I clone the git and go build, what is the difference?

**Comment by limbo127** [comment]
With Makefile ( ok for the using -X ) , same error with the test. 
make 
which: no termbacktime in (/home/xxx/.local/bin:/home/xx/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin:/usr/local/go/bin)
which: no termbacktime-dev in (/home/xx/.local/bin:/home/xx/bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/var/lib/snapd/snap/bin:/usr/local/go/bin)
go clean
rm -rf ./builds/termbacktime*
go vet ./...
go build -o ./builds/termbacktime -v -ldflags "-s -w -X 'louist.dev/termbacktime/cmd.Application=termbacktime' -X 'louist.dev/termbacktime/cmd.Version=v1.0.0-rc.8' -X 'louist.dev/termbacktime/cmd.Revision=7a61ca1' -X 'louist.dev/termbacktime/cmd.PlaybackURL=https://termbackti.me'  -X 'louist.dev/termbacktime/cmd.GistAPI=https://api.github.com/gists' -X 'louist.dev/termbacktime/cmd.Broker=wss://broker.termbackti.me' -X 'louist.dev/termbacktime/cmd.GistFileName=terminal-recording.json' -X 'louist.dev/termbacktime/cmd.ConfigType=json' -X 'louist.dev/termbacktime/cmd.STUNServerOne=stun:stun1.l.google.com:19302' -X 'louist.dev/termbacktime/cmd.STUNServerTwo=stun:stun2.l.google.com:19302' -X 'louist.dev/termbacktime/cmd.APIEndpoint=https://api.termbackti.me' -X 'louist.dev/termbacktime/cmd.LiveURL=https://xterm.live'"
[xxxx@localhost termbacktime]$ ls builds/
termbacktime
[xxx@localhost termbacktime]$ builds/termbacktime live
Loaded config: /home/xxx/.termbacktime.json

Access granted: [turn:turn.termbackti.me:5349]
Username: 1645003497-ef88a6a5-327f-4aaa-89a4-bef471045497
Password: bVXa0Fk7VuuMir9e9Y/PfffHPa4=

Live playback: https://xterm.live/tbt:c231a791-d917-4571-86bb-1ff128146c14
Waiting for connection; timeout in 113 seconds... Connected.

**connect with firefox** 

Error: unexpected EOF

panic: close of closed channel

goroutine 118 [running]:
louist.dev/termbacktime/cmd.glob..func4.7()
	/tmp/termbacktime/cmd/live.go:229 +0x6ce
created by louist.dev/termbacktime/cmd.glob..func4
	/tmp/termbacktime/cmd/live.go:223 +0x1fa5
[xxx@localhost termbacktime]$ cat /home/xxx/.termbacktime.json
{
  "login": "8f476e89-bae0-4649-b07f-45a4930e7740",
  "version-check": true
}

**Comment by LouisT** [comment]
Sorry this took a while to address, I had a hard time figuring out what the issue was. The most recent merge to master should fix the problem. Could you please pull and try again. Thanks.

**Comment by LouisT** [comment]
Seems to be fixed, feel free to re-open if I'm wrong.
