### ISSUE TITLE
trying but fail

### ISSUE THREAD

**Issue by limbo127** [LouisT/termbacktime#98]
Hello, 
i'm trying a live termbacktime without success
1 - test on same machine
Access granted: [turn:turn.termbackti.me:5349]
Username: 1644836944-5a0b3944-a19b-437b-997c-3f1f95d7a283
Password: lHKsaLUBvpPzqzfo+7ML4+EW2mw=

Live playback: https://xterm.live/tbt:79328449-1977-42ed-8712-dbe6ca8c276c
Waiting for connection; timeout in 90 seconds... Connected.

Error: websocket: close 1005 (no status)

panic: close of closed channel

goroutine 104 [running]:
louist.dev/termbacktime/cmd.glob..func4.7()
	/tmp/tmp.nomJ4tPTFP/cmd/live.go:229 +0x6ce
created by louist.dev/termbacktime/cmd.glob..func4
	/tmp/tmp.nomJ4tPTFP/cmd/live.go:223 +0x1fa5

2 - trying with 2 differents machine, with two internet connection

Access granted: [turn:turn.termbackti.me:5349]
Username: 1644837120-e6f0bcfa-406a-4626-872c-773921d0f636
Password: f8ljc+tNnOh66qnnd1qhleI7zPY=

Live playback: https://xterm.live/tbt:ee857939-ef8a-4fdd-8ad4-aa9a57b74a4f
Waiting for connection; timeout in 89 seconds... Connected.

Error: unexpected EOF

panic: close of closed channel

goroutine 117 [running]:
louist.dev/termbacktime/cmd.glob..func4.7()
	/tmp/tmp.nomJ4tPTFP/cmd/live.go:229 +0x6ce
created by louist.dev/termbacktime/cmd.glob..func4
	/tmp/tmp.nomJ4tPTFP/cmd/live.go:223 +0x1fa5

**Comment by LouisT** [comment]
I need a bit more information on this. I'm going to close this ticket; can you please recreate it using the issue template I've added. Thanks. https://github.com/termbacktime/termbacktime#reporting-issues
